version: "3"

services:
  app:
    container_name: "app"
    build:
      dockerfile: Dockerfile
    # volumes:
      # - ..:/workspaces:cached
    depends_on:
      - postgresdb
      - grafana
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgresdb:
    container_name: "postgres"
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
  grafana:
    container_name: "grafana"
    image: grafana/grafana-oss:10.4.1
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - postgresdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  postgres-data:
  grafana-storage:
