version: "3"

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - postgresdb
      - grafana
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgresdb:
    container_name: "postgresdb"
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  grafana:
    container_name: "grafana"
    image: grafana/grafana-oss:10.4.1
    volumes:
      - grafana-data:/var/lib/grafana:rw
    depends_on:
      - postgresdb
    ports:
      - ${GRAFANA_PORT}:3000
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  postgres-data:
  grafana-data:
  